import React from "react"
import Head from "next/head"

import { CustomCursor, Frames, Sound } from "../components"

const Home = () => {
  return (
    <>
      <Head>
        <title>Beautiful World - 3D Scroll</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full h-full fixed perspective">
        <CustomCursor />

        <section className="h-full transform-3d">
          <Frames />
        </section>
      </main>

      <Sound />
    </>
  )
}

export default Home
